[package]
name = "currency-converter"
version = "0.1.0"
edition = "2024"

[dependencies]
cashify = "0.1"
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
